### ISSUE TITLE
Document the new login endpoint

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/api-documentation#19]
- openfoodfacts/openfoodfacts-server/pull/5240

**Comment by M123-dev** [comment]
I can do that

**Comment by teolemon** [comment]
@M123-dev I added a starter in the PR #33

**Comment by teolemon** [comment]
https://openfoodfacts.github.io/api-documentation-staging/#1GeneralInformation

**Comment by M123-dev** [comment]
Should the user creation also be included in the documentation or should this rather be reserved for the own apps

**Comment by teolemon** [comment]
It's worth documenting in both cases 👍

**Comment by M123-dev** [comment]
@teolemon where should I add these, perhaps a new authentication folder

**Comment by teolemon** [comment]
Yes, that sounds good
