### ISSUE TITLE
GSOD'22

### ISSUE THREAD

**Issue by Shorla** [openfoodfacts/api-documentation#82]
Hi, my name is Shola and I am a GSOD'22 applicant. I was going through the GSOD Proposal and didn't see a way to apply to the community. How is the statement of interest to be submitted? Are we required to work with the community beforehand?

**Comment by teolemon** [comment]
Sorry for the delay @Shorla, are you already on Slack ? (https://slack.openfoodfacts.org)
I've also created a form to manifest your interest: https://forms.gle/8ME8RoGDVUw3r8cK9

**Comment by Shorla** [comment]
@teolemon, thanks. I joined the slack channel already.
